/**
 * รายการค่าลดหย่อนภาษีเงินได้บุคคลธรรมดาตั้งต้น
 * -----------------------------------------------------------------------------
 * ใช้เป็นค่าเริ่มต้นตอนสร้างปีภาษีใหม่เท่านั้น หลังสร้างแล้วบริษัทแก้ได้เองทุกช่อง
 * (กฎหมายภาษีปรับเพดานเกือบทุกปี ระบบจึงต้องแก้ได้โดยไม่ต้องแก้โค้ด)
 *
 * ตัวเลขอ้างอิงประมวลรัษฎากรที่ใช้อยู่ ณ ปีภาษี 2568
 * ถ้ากรมสรรพากรประกาศเปลี่ยน ให้แก้ที่หน้าตั้งค่าปีภาษี ไม่ต้องแก้ไฟล์นี้
 */

/** กลุ่มเพดานรวม — ใช้กับกฎที่จำกัดหลายประเภทรวมกัน */
export const DEFAULT_ALLOWANCE_LIMIT_GROUPS = [
  {
    code: 'RETIREMENT_FUND',
    nameTh: 'กองทุนเพื่อการเกษียณและประกันบำนาญ',
    maxAmount: 500000,
    maxPercentOfIncome: null,
    percentBase: 'GROSS_INCOME',
    isSystem: true,
    sortOrder: 10,
    note: 'กบข. + กองทุนสำรองเลี้ยงชีพ + RMF + SSF + กอช. + ประกันชีวิตแบบบำนาญ รวมกันไม่เกิน 500,000 บาท',
  },
  {
    code: 'LIFE_HEALTH_INSURANCE',
    nameTh: 'ประกันชีวิตและประกันสุขภาพตนเอง',
    maxAmount: 100000,
    maxPercentOfIncome: null,
    percentBase: 'GROSS_INCOME',
    isSystem: true,
    sortOrder: 20,
    note: 'เบี้ยประกันชีวิตรวมกับเบี้ยประกันสุขภาพตนเอง ไม่เกิน 100,000 บาท (ส่วนประกันสุขภาพเองไม่เกิน 25,000)',
  },
  {
    code: 'DONATION',
    nameTh: 'เงินบริจาค',
    maxAmount: null,
    maxPercentOfIncome: 0.1,
    percentBase: 'NET_AFTER_ALLOWANCE',
    isSystem: true,
    sortOrder: 30,
    note: 'กฎหมายให้หักบริจาคการศึกษา 2 เท่าก่อน แล้วบริจาคทั่วไปคิดจากยอดที่เหลือ ระบบใช้เพดานรวม 10% ของเงินได้หลังหักค่าใช้จ่ายและค่าลดหย่อน ซึ่งได้ผลเท่ากันเมื่อยอดไม่ชนเพดาน',
  },
] as const;

/**
 * ประเภทค่าลดหย่อน
 *
 * maxPercentOfIncome: 0.15 = 15% — ว่างคือไม่จำกัดด้วยสัดส่วน
 * limitGroupCode: อ้างถึง code ใน DEFAULT_ALLOWANCE_LIMIT_GROUPS
 * ถ้าประเภทไหนตั้งทั้งเพดานจำนวนเงินและเพดานสัดส่วน ระบบใช้อันที่แคบกว่า
 */
export const DEFAULT_ALLOWANCE_TYPES = [
  /* ---- ค่าลดหย่อนส่วนตัวและครอบครัว ---- */
  {
    code: 'PERSONAL',
    nameTh: 'ค่าลดหย่อนส่วนตัว',
    category: 'STANDARD',
    defaultAmount: 60000,
    maxAmount: 60000,
    isSystem: true,
    sortOrder: 10,
  },
  {
    code: 'SPOUSE',
    nameTh: 'คู่สมรสไม่มีเงินได้',
    category: 'FAMILY',
    defaultAmount: 60000,
    maxAmount: 60000,
    isSystem: true,
    sortOrder: 20,
  },
  {
    code: 'CHILD',
    nameTh: 'บุตร',
    category: 'FAMILY',
    defaultAmount: 30000,
    maxAmount: null,
    isSystem: true,
    sortOrder: 30,
    note: 'คนละ 30,000 บาท ไม่จำกัดจำนวนบุตรชอบด้วยกฎหมาย · บุตรคนที่ 2 ขึ้นไปที่เกิดตั้งแต่ปี 2561 หักได้คนละ 60,000 บาท',
  },
  {
    code: 'PARENT',
    nameTh: 'บิดามารดา',
    category: 'FAMILY',
    defaultAmount: 30000,
    maxAmount: 120000,
    isSystem: true,
    sortOrder: 40,
    note: 'คนละ 30,000 บาท ได้สูงสุด 4 คน (บิดามารดาของตนเองและของคู่สมรส)',
  },
  {
    code: 'DISABLED_CARE',
    nameTh: 'อุปการะคนพิการหรือทุพพลภาพ',
    category: 'FAMILY',
    defaultAmount: 0,
    maxAmount: null,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 45,
    note: 'คนละ 60,000 บาท ต้องมีบัตรประจำตัวคนพิการหรือใบรับรองแพทย์',
  },
  {
    code: 'PRENATAL_CARE',
    nameTh: 'ค่าฝากครรภ์และค่าคลอดบุตร',
    category: 'FAMILY',
    defaultAmount: 0,
    maxAmount: 60000,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 48,
    note: 'ตามที่จ่ายจริง ไม่เกินท้องละ 60,000 บาท',
  },

  /* ---- เบี้ยประกัน ---- */
  {
    code: 'LIFE_INSURANCE',
    nameTh: 'เบี้ยประกันชีวิต',
    category: 'INSURANCE',
    defaultAmount: 0,
    maxAmount: 100000,
    limitGroupCode: 'LIFE_HEALTH_INSURANCE',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 50,
    note: 'กรมธรรม์ต้องมีกำหนดเวลาตั้งแต่ 10 ปีขึ้นไป',
  },
  {
    code: 'HEALTH_INSURANCE',
    nameTh: 'เบี้ยประกันสุขภาพตนเอง',
    category: 'INSURANCE',
    defaultAmount: 0,
    maxAmount: 25000,
    limitGroupCode: 'LIFE_HEALTH_INSURANCE',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 55,
    note: 'ไม่เกิน 25,000 บาท และเมื่อรวมกับเบี้ยประกันชีวิตต้องไม่เกิน 100,000 บาท',
  },
  {
    code: 'SPOUSE_LIFE_INSURANCE',
    nameTh: 'เบี้ยประกันชีวิตคู่สมรสไม่มีเงินได้',
    category: 'INSURANCE',
    defaultAmount: 0,
    maxAmount: 10000,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 58,
  },
  {
    code: 'PARENT_HEALTH_INSURANCE',
    nameTh: 'เบี้ยประกันสุขภาพบิดามารดา',
    category: 'INSURANCE',
    defaultAmount: 0,
    maxAmount: 15000,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 60,
    note: 'บิดามารดาต้องมีเงินได้ไม่เกิน 30,000 บาทต่อปี',
  },
  {
    code: 'PENSION_INSURANCE',
    nameTh: 'เบี้ยประกันชีวิตแบบบำนาญ',
    category: 'INSURANCE',
    defaultAmount: 0,
    maxAmount: 200000,
    maxPercentOfIncome: 0.15,
    limitGroupCode: 'RETIREMENT_FUND',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 62,
    note: 'ไม่เกิน 15% ของเงินได้ และไม่เกิน 200,000 บาท',
  },

  /* ---- ประกันสังคม ---- */
  {
    // เพดานจริงคำนวณจากเพดานฐานประกันสังคมของบริษัทตอนคิดภาษี
    // (ดู resolveSocialSecurityAllowance) ค่าที่ตั้งตรงนี้ใช้แสดงในหน้าตั้งค่าเท่านั้น
    // จึงตั้งให้ตรงกับเพดานฐานตั้งต้น 17,500 × 5% × 12 = 10,500
    code: 'SOCIAL_SECURITY',
    nameTh: 'เงินสมทบประกันสังคม',
    category: 'SOCIAL_SECURITY',
    defaultAmount: 0,
    maxAmount: 10500,
    isSystem: true,
    sortOrder: 65,
  },

  /* ---- กองทุน ---- */
  {
    code: 'PROVIDENT_FUND',
    nameTh: 'กองทุนสำรองเลี้ยงชีพ',
    category: 'FUND',
    defaultAmount: 0,
    maxAmount: 500000,
    maxPercentOfIncome: 0.15,
    limitGroupCode: 'RETIREMENT_FUND',
    isSystem: true,
    sortOrder: 70,
    note: 'เฉพาะเงินสะสมส่วนของลูกจ้าง ไม่เกิน 15% ของค่าจ้าง',
  },
  {
    code: 'GPF',
    nameTh: 'กองทุนบำเหน็จบำนาญข้าราชการ (กบข.)',
    category: 'FUND',
    defaultAmount: 0,
    maxAmount: 500000,
    maxPercentOfIncome: 0.3,
    limitGroupCode: 'RETIREMENT_FUND',
    isSystem: true,
    status: 'INACTIVE',
    sortOrder: 72,
    note: 'ใช้กับหน่วยงานราชการ ปิดไว้ตั้งต้น เปิดใช้เมื่อจำเป็น',
  },
  {
    code: 'RMF',
    nameTh: 'กองทุนรวมเพื่อการเลี้ยงชีพ (RMF)',
    category: 'FUND',
    defaultAmount: 0,
    maxAmount: 500000,
    maxPercentOfIncome: 0.3,
    limitGroupCode: 'RETIREMENT_FUND',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 75,
    note: 'ไม่เกิน 30% ของเงินได้ และไม่เกิน 500,000 บาท',
  },
  {
    code: 'SSF',
    nameTh: 'กองทุนรวมเพื่อการออม (SSF)',
    category: 'FUND',
    defaultAmount: 0,
    maxAmount: 200000,
    maxPercentOfIncome: 0.3,
    limitGroupCode: 'RETIREMENT_FUND',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 78,
    note: 'ไม่เกิน 30% ของเงินได้ และไม่เกิน 200,000 บาท',
  },
  {
    code: 'NSF',
    nameTh: 'กองทุนการออมแห่งชาติ (กอช.)',
    category: 'FUND',
    defaultAmount: 0,
    maxAmount: 30000,
    limitGroupCode: 'RETIREMENT_FUND',
    isSystem: true,
    sortOrder: 80,
  },
  {
    code: 'THAI_ESG',
    nameTh: 'กองทุนรวมไทยเพื่อความยั่งยืน (Thai ESG)',
    category: 'FUND',
    defaultAmount: 0,
    maxAmount: 300000,
    maxPercentOfIncome: 0.3,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 82,
    note: 'นับแยกจากเพดานรวม 500,000 ของกลุ่มกองทุนเกษียณ',
  },

  /* ---- ดอกเบี้ยและการลงทุน ---- */
  {
    code: 'HOME_LOAN_INTEREST',
    nameTh: 'ดอกเบี้ยเงินกู้ยืมเพื่อที่อยู่อาศัย',
    category: 'LOAN',
    defaultAmount: 0,
    maxAmount: 100000,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 85,
    note: 'ตามที่จ่ายจริง ไม่เกิน 100,000 บาท ต้องมีหนังสือรับรองดอกเบี้ยจากสถาบันการเงิน',
  },
  {
    code: 'SOCIAL_ENTERPRISE',
    nameTh: 'เงินลงทุนในวิสาหกิจเพื่อสังคม',
    category: 'INVESTMENT',
    defaultAmount: 0,
    maxAmount: 100000,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 88,
  },

  /* ---- เงินบริจาค (คิดจากเงินได้หลังหักค่าใช้จ่ายและค่าลดหย่อนอื่น) ---- */
  {
    code: 'DONATION_EDUCATION',
    nameTh: 'เงินบริจาคเพื่อการศึกษา กีฬา และพัฒนาสังคม',
    category: 'DONATION',
    defaultAmount: 0,
    maxAmount: null,
    deductionMultiplier: 2,
    percentBase: 'NET_AFTER_ALLOWANCE',
    limitGroupCode: 'DONATION',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 90,
    note: 'หักได้ 2 เท่าของที่จ่ายจริง แต่เมื่อรวมเงินบริจาคทั้งหมดต้องไม่เกิน 10% ของเงินได้หลังหักค่าใช้จ่ายและค่าลดหย่อน',
  },
  {
    code: 'DONATION_GENERAL',
    nameTh: 'เงินบริจาคทั่วไป',
    category: 'DONATION',
    defaultAmount: 0,
    maxAmount: null,
    percentBase: 'NET_AFTER_ALLOWANCE',
    limitGroupCode: 'DONATION',
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 92,
  },
  {
    code: 'POLITICAL_DONATION',
    nameTh: 'เงินบริจาคให้พรรคการเมือง',
    category: 'DONATION',
    defaultAmount: 0,
    maxAmount: 10000,
    requiresAttachment: true,
    isSystem: true,
    sortOrder: 95,
  },
] as const;
